spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    #    password: root1234  ?? ???
    driver-class-name: com.mysql.cj.jdbc.Driver

  #    jwt ??? ??
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          서비스명:
            client-name: 서비스명
            client-id: 서비스에서 발급 받은 아이디
            client-secret: 서비스에서 발급 받은 비밀번호
            redirect-uri: 서비스에 등록한 우리쪽 로그인 성공 URI
            authorization-grant-type: authorization_code
            scope: 리소스 서버에서 가져올 데이터 범위
        provider:
          서비스명:
            authorization-uri: 서비스 로그인 창 주소
            token-uri: 토큰 발급 서버 주소
            user-info-uri: 사용자 정보 획득 주소
            user-name-attribute: 응답 데이터 변수


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
